name: Build Driver App APK

on:
  workflow_dispatch: # This allows you to manually trigger the build from GitHub UI

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Prebuild Expo Project
        working-directory: ./mobile-app/driver-app
        run: npx expo prebuild -p android

      - name: Build APK with Gradle
        working-directory: ./mobile-app/driver-app/android
        run: chmod +x gradlew && ./gradlew assembleRelease --stacktrace --info

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: driver-app-apk
          path: mobile-app/driver-app/android/app/build/outputs/apk/release/app-release.apk
